# fly.toml app configuration file generated for kindle-ai-audiobook on 2025-11-17T19:11:54-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'kindle-ai-audiobook'
primary_region = 'iad'

[build]
  dockerfile = 'Dockerfile'

[env]
  HOST = '0.0.0.0'
  PORT = '3000'
  TLS_PROXY_HEALTH_PORT = '8081'
  TLS_PROXY_PORT = '8080'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 30
    soft_limit = 25

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
